### ISSUE TITLE
Tweak details view

### ISSUE THREAD

**Issue by fsteeg** [hbz/digitalisiertedrucke#11]
- [ ] emphasize fulltext link (icon, header)
- [ ] compact table
- [ ] resource name as page title (displayed in browser tab)
- [ ] display subjects label only if there are any: http://dd.lobid.org/collections/j_m_r_lenz.uni-ma.ma.de

**Comment by acka47** [comment]
Also:

- [ ] Don't show id field
- [ ] Improve order

**Comment by acka47** [comment]
Generally, we should merge information on digitized and the printed source resources into one entry. So that we only have "Sammlungen" and "Titel" (probably with another term) as main types. This is also on the search level. I better make a separate issue for this, shouldn't I?

**Comment by SBRitter** [comment]
And:
- [ ] Add collection to print/digital view

**Comment by fsteeg** [comment]
For reference, a details page in the old system:
http://web.archive.org/web/20130327065029/http://www.digitalisiertedrucke.de/record/491272?ln=de

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.digitalisiertedrucke.de/resources/P323128
http://test.digitalisiertedrucke.de/collections/pressedienst_1946-1995.fes.bn.de

**Comment by acka47** [comment]
The order of metadata elements for collections should be improved. For reference:

Old version: http://web.archive.org/web/20100213014249/http://www.digitalisiertedrucke.de/record/46777?ln=de
New version: http://test.digitalisiertedrucke.de/collections/drucke_reformationszeit.sl.wb.de

**Comment by acka47** [comment]
Also http://web.archive.org/web/20100213014337/http://www.digitalisiertedrucke.de/record/46780?ln=de vs. http://test.digitalisiertedrucke.de/collections/druckwerke_leibnizzeit.hab.wf.de. What I noticed is:

- We display data that wasn't displayed in the old version: Sprache, Umfang (While "Sprache" is important we should probably remove extent information from collections.)
- We don't display data that was in the old version: Digitalisierungszeitrauzm, Zeitliche Abdeckung

**Comment by fsteeg** [comment]
Why remove the extent information from collections? Seems useful.

For missing data: #38 

Tweaked order deployed to staging:

http://test.digitalisiertedrucke.de/collections/einblattdrucke.vd17.oo.de
http://test.digitalisiertedrucke.de/collections/drucke_reformationszeit.sl.wb.de
http://test.digitalisiertedrucke.de/collections/archaeologische_funde.hab.wf.de

Compare to:

http://web.archive.org/web/20100213014352/http://www.digitalisiertedrucke.de/record/46783?ln=de
http://web.archive.org/web/20100213014249/http://www.digitalisiertedrucke.de/record/46777?ln=de
http://web.archive.org/web/20100213014342/http://www.digitalisiertedrucke.de/record/46781?ln=de

Two ideas for new issues based on the old versions:

- Add query for contained titles to the collection details view
- Add a footer with the details from the old version (partners etc.)

**Comment by fsteeg** [comment]
One more pretty complete collection details view:

http://test.digitalisiertedrucke.de/collections/druckwerke_leibnizzeit.hab.wf.de

**Comment by acka47** [comment]
Please use "Siehe auch" instead "Thema von". After this: +1

**Comment by fsteeg** [comment]
Deployed to staging:

http://test.digitalisiertedrucke.de/collections/druckwerke_leibnizzeit.hab.wf.de

**Comment by acka47** [comment]
+1
