### ISSUE TITLE
Set up digitalisiertedrucke.de domain

### ISSUE THREAD

**Issue by fsteeg** [hbz/digitalisiertedrucke#12]
We could set up the domain before we launch and set up proxies like this:

- [x] digitalisiertedrucke.de `->` current page
- [x] www.digitalisiertedrucke.de `->` current page
- [x] beta.digitalisiertedrucke.de `->` http://dd.lobid.org
- [x] test.digitalisiertedrucke.de `->`  http://dd-test.lobid.org

Or we work with the lobid.org domains and do the domain switch in the end.

**Comment by acka47** [comment]
We should obtain control over digitalisiertedrucke.de ASAP. Especially, because I would like to take a look at the old site via http://web.archive.org/web/*/http://digitalisiertedrucke.de. Unfortunately, the pages won't be displayed because of the [robots.txt](http://www.digitalisiertedrucke.de/robots.txt) which currently reads like this:

> User-Agent: *
Disallow: /

**Comment by acka47** [comment]
We will talk about how to proceed on Thursday with @dr0i who has more experience with these things.

**Comment by fsteeg** [comment]
In our discussion, we decided to set up 3 proxies:

- dd.lobid.org -> current digitalisiertedrucke.de content
- dd-beta.lobid.org -> new beta system
- dd-test.lobid.org -> testing new system

We will then point the digitalisiertedrucke.de domain to emphytos, and rename the vhosts accordingly.

**Comment by fsteeg** [comment]
I've set up the three instances:

- http://dd.lobid.org/
- http://dd-beta.lobid.org/
- http://dd-test.lobid.org/

We can now direct the digitalisiertedrucke.de DNS to emphytos, and rename/update the vhosts.

**Comment by dr0i** [comment]
I suggest to rename/update the vhost *before* directing digitalisiertedrucke.de to emphytos - otherwise there will be downtime.

**Comment by dr0i** [comment]
Wrote to our IT to change the DNS for digitalisiertedrucke.de and their respective subdomains (note, I added the `www`-subdomain (and edited the first comment of this issue). In fact, and strangely so, the www-domain was the only one configured in the old DNS).

**Comment by dr0i** [comment]
DNS is changed.

**Comment by fsteeg** [comment]
Great, DNS looks good, and it actually works to browse the archived versions now. Latest with content seems to be this: http://web.archive.org/web/20141021154304/http://www.digitalisiertedrucke.de/

**Comment by fsteeg** [comment]
Here is an archived result list:
http://web.archive.org/web/20140403235935/http://www.digitalisiertedrucke.de/collection/Digitale%20Sammlungen

And here is an archived details view:
http://web.archive.org/web/20130327065029/http://www.digitalisiertedrucke.de/record/491272?ln=de

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
Closing.
