### ISSUE TITLE
Support format=json on individual titles and collections

### ISSUE THREAD

**Issue by fsteeg** [hbz/digitalisiertedrucke#14]
e.g. http://dd.lobid.org/resources/P73301?format=json

Like http://dd.lobid.org/?q=*&format=json

**Comment by fsteeg** [comment]
Deployed to staging:

http://test.digitalisiertedrucke.de/resources/P321697?format=json
http://test.digitalisiertedrucke.de/resources/D321697?format=json
http://test.digitalisiertedrucke.de/collections/pressedienst_1946-1995.fes.bn.de?format=json

**Comment by acka47** [comment]
+1 Please also pretty print, see https://github.com/hbz/lobid-organisations/issues/85 and @dr0i's solution in https://github.com/hbz/lobid-resources/issues/105.

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.digitalisiertedrucke.de/resources/P321697?format=json
http://test.digitalisiertedrucke.de/resources/D321697?format=json
http://test.digitalisiertedrucke.de/collections/pressedienst_1946-1995.fes.bn.de?format=json
http://test.digitalisiertedrucke.de/?q=*&format=json

**Comment by acka47** [comment]
+1
