### ISSUE TITLE
Set up robots.txt to avoid indexing of test.digitalisiertedrucke.de

### ISSUE THREAD

**Issue by fsteeg** [hbz/digitalisiertedrucke#22]
Also beta.digitalisiertedrucke.de?

**Comment by fsteeg** [comment]
Deployed to staging: http://test.digitalisiertedrucke.de/robots.txt

Checked with http://tool.motoricerca.info/robots-checker.phtml

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
I guess we should also disallow crawling beta.
