### ISSUE TITLE
Errors on some resource details pages

### ISSUE THREAD

**Issue by fsteeg** [hbz/digitalisiertedrucke#25]
See hits with URI links at:
http://test.digitalisiertedrucke.de/?from=0&size=20&q=*+AND+isPartOf:%22http://digitalisiertedrucke.de/collections/zvdd.hbz.k.de%22

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.digitalisiertedrucke.de/resources/D46647
http://test.digitalisiertedrucke.de/resources/D46669
http://test.digitalisiertedrucke.de/resources/D46682
http://test.digitalisiertedrucke.de/resources/D46713

**Comment by acka47** [comment]
+1
