### ISSUE TITLE
Errors with collections we have no or missing data

### ISSUE THREAD

**Issue by fsteeg** [hbz/digitalisiertedrucke#26]
Some collections don't get a title, see collections facet ('Teil von') at:
http://test.digitalisiertedrucke.de/?q=*

These collections also fail when accessed directly, like:
http://test.digitalisiertedrucke.de/collections/zvdd.hbz.k.de

They are linked from the digitized titles:
http://test.digitalisiertedrucke.de/resources/D28648?format=json
(note the links point to the non-test instance, using test for latest fixes.)

**Comment by fsteeg** [comment]
Deployed to staging.

Missing collections return proper response:
http://test.digitalisiertedrucke.de/collections/zvdd.hbz.k.de

Our own super-collection lists its collections: 
http://test.digitalisiertedrucke.de/collections

This fixes the web level issues.

Will open a separate issue for the actual missing data.

**Comment by fsteeg** [comment]
Data issue: #32

**Comment by acka47** [comment]
+1
