### ISSUE TITLE
Missing collections

### ISSUE THREAD

**Issue by fsteeg** [hbz/digitalisiertedrucke#32]
Missing collections:
- http://test.digitalisiertedrucke.de/collections/einblattdrucke_vd17.gbv.goe.de
- http://test.digitalisiertedrucke.de/collections/digiwunsch.sub.goe.de
- http://test.digitalisiertedrucke.de/collections/digitale_sammlungen.uni.bn.de
- http://test.digitalisiertedrucke.de/collections/die_arbeit.fes.bn.de
- http://test.digitalisiertedrucke.de/collections/sozialistische_monatshefte.fes.bn.de
- http://test.digitalisiertedrucke.de/collections/sammlung_ponickau.ulb.hal.de
- http://test.digitalisiertedrucke.de/collections/juedische_periodika.rwth.ac.de
- http://test.digitalisiertedrucke.de/collections/zvdd.gbv.goe.de
- http://test.digitalisiertedrucke.de/collections/zvdd.hbz.k.de

But they have associated titles:
- http://test.digitalisiertedrucke.de/?q=*%20AND%20isPartOf:%22http://digitalisiertedrucke.de/collections/einblattdrucke_vd17.gbv.goe.de%22
- http://test.digitalisiertedrucke.de/?q=*+AND+isPartOf:%22http://digitalisiertedrucke.de/collections/digiwunsch.sub.goe.de%22
- http://test.digitalisiertedrucke.de/?q=*+AND+isPartOf:%22http://digitalisiertedrucke.de/collections/digitale_sammlungen.uni.bn.de%22
- http://test.digitalisiertedrucke.de/?q=*+AND+isPartOf:%22http://digitalisiertedrucke.de/collections/die_arbeit.fes.bn.de%22
- http://test.digitalisiertedrucke.de/?q=*+AND+isPartOf:%22http://digitalisiertedrucke.de/collections/sozialistische_monatshefte.fes.bn.de%22
- http://test.digitalisiertedrucke.de/?q=*+AND+isPartOf:%22http://digitalisiertedrucke.de/collections/sammlung_ponickau.ulb.hal.de%22
- http://test.digitalisiertedrucke.de/?q=*+AND+isPartOf:%22http://digitalisiertedrucke.de/collections/juedische_periodika.rwth.ac.de%22
- http://test.digitalisiertedrucke.de/?q=*+AND+isPartOf:%22http://digitalisiertedrucke.de/collections/zvdd.gbv.goe.de%22
- http://test.digitalisiertedrucke.de/?q=*+AND+isPartOf:%22http://digitalisiertedrucke.de/collections/zvdd.hbz.k.de%22

**Comment by fsteeg** [comment]
This is weird. The old website lists 146 collections [1], we have 147 (the additional 1 is probably our own supercollection), so this does not fit with 9 missing collections. Maybe these are wrong collection IDs? In the old system, the collections have numerical IDs like the resources, see links in [1], while we use the content of `992  a` as the ID. That's a custom field, right? @dr0i, do you remember why you picked that?

The collections have a `024` field, which sounds like the thing to use for the ID [2]:

```
<marc:datafield ind1="8" ind2=" " tag="024">
    <marc:subfield code="a">oai:digitalisiertedrucke.de:46713</marc:subfield>
    <marc:subfield code="p">collection</marc:subfield>
</marc:datafield>
```

Would it make sense to use that number as the ID? It would yield URIs like `http://digitalisiertedrucke/collections/46713` for collections, instead of the current `http://digitalisiertedrucke/collections/feldzeitungen.ub.hd.de`. Don't know if that would solve the issue here, but it seems more correct to me. It might also fix some other collection-related issues we have.

[1] http://web.archive.org/web/20130526203147/http://www.digitalisiertedrucke.de/collection/Sammlungsbeschreibungen?ln=de
[2] https://www.loc.gov/marc/bibliographic/bd024.html

**Comment by acka47** [comment]
+1 for using the ID from 024 for collections.

**Comment by fsteeg** [comment]
After some further discussion with @acka47 we figured that the `001` actually contains the ID.

I had tested this with our current system and we get a resource with the same ID as the collection (see http://beta.digitalisiertedrucke.de/resources/46713), but that seems to be due to some kind of error, since the 001 IDs are actually unique:

```
$ cat hbz_zvdd_resource_marc.xml | grep "tag=\"001\"" | wc -l
491271
$ cat hbz_zvdd_resource_marc.xml | grep "tag=\"001\"" | sort -u | wc -l
491271
```

With this approach, we can also reconstruct the old URLs like 
`http://digitalisiertedrucke.de/record/46713` (I'll open a separate issue for that).

**Comment by dr0i** [comment]
sounds reasonable. +1

**Comment by fsteeg** [comment]
So here's the problem: in the 024 field in https://github.com/hbz/digitalisiertedrucke/issues/32#issuecomment-255364712, the `a` subfield's ID is not the collection from the `p` subfield, but the ID of the title resource itself. See title MAB-MXL in [1].

So it seems the `isPartOf` relationship is only expressed in our data with the IDs we used before. I guess this was the reason @dr0i used that as the ID when he originally wrote the transformation.

We could either stick with the current IDs, or implement a mapping from these to the numerical ones.

This affects #45 (restoring old URLs).

What do you think @acka47?

[1] https://github.com/hbz/digitalisiertedrucke/wiki/Example-resources

**Comment by acka47** [comment]
@dr0i and me just sat down to understand this. It seems as it was decided to not add any collection descriptions at the end of digitalisiertedrucke but to only create collections by linking records together. That's why  8-9 collections are missing. We already created rudimentary descriptions for these with https://github.com/lobid/lodmill/blob/master/lodmill-rd/transformations/zvdd/data/missing_collections.ttl. These should just be added to the data. For two collections there is no description, though: collection:einblattdrucke_vd17.gbv.goe.de & collections:zvdd.hbz.k.de. The first probably is an error and we should use collection:einblattdrucke.vd17.oo.de instead (see also https://github.com/lobid/lodmill/blob/master/lodmill-rd/transformations/zvdd/statistic/mismatching_collection-IDs.textile). The second is the super collection for all other collection. I think we can completely discard it in the UI.

Regarding the identifiers, we should keep using the literal ones for collections and  look into using the /record/$ID pattern for single resources. Thus, we would regain old URLs for the biggest part of resources.

**Comment by acka47** [comment]
As discussed with @fsteeg today, I will add the data from https://github.com/lobid/lodmill/blob/master/lodmill-rd/transformations/zvdd/data/missing_collections.ttl as JSON to https://github.com/hbz/digitalisiertedrucke/tree/master/conf.

**Comment by fsteeg** [comment]
Deployed to staging:

- http://test.digitalisiertedrucke.de/collections/digiwunsch.sub.goe.de
- http://test.digitalisiertedrucke.de/collections/digitale_sammlungen.uni.bn.de
- http://test.digitalisiertedrucke.de/collections/die_arbeit.fes.bn.de
- http://test.digitalisiertedrucke.de/collections/sozialistische_monatshefte.fes.bn.de
- http://test.digitalisiertedrucke.de/collections/sammlung_ponickau.ulb.hal.de
- http://test.digitalisiertedrucke.de/collections/juedische_periodika.rwth.ac.de
- http://test.digitalisiertedrucke.de/collections/zvdd.gbv.goe.de

Will implement URL pattern as described in https://github.com/hbz/digitalisiertedrucke/issues/32#issuecomment-256020938 in #45.

**Comment by acka47** [comment]
+1
