### ISSUE TITLE
Missing resource details

### ISSUE THREAD

**Issue by fsteeg** [hbz/digitalisiertedrucke#38]
In the original system, resources have a creation date and an extent field, see http://web.archive.org/web/20130327065029/http://www.digitalisiertedrucke.de/record/491272?ln=de

In our current data, these are not present:
http://test.digitalisiertedrucke.de/resources/D491272?format=json
http://test.digitalisiertedrucke.de/resources/P491272?format=json

Publisher field looks incomplete too ('Universitäts- und Landesbibliothek').

**Comment by fsteeg** [comment]
Deployed to staging: http://test.digitalisiertedrucke.de/resources/D491272

**Comment by acka47** [comment]
+1
