### ISSUE TITLE
Add query for contained titles to the collection details view

### ISSUE THREAD

**Issue by acka47** [hbz/digitalisiertedrucke#40]
Add link "Enthaltene Titel anzeigen".

**Comment by fsteeg** [comment]
Deployed to staging, see:

- http://test.digitalisiertedrucke.de/collections/camena_historica_politica.uni.hd.de
- http://test.digitalisiertedrucke.de/collections/archaeologische_literatur.ub.hd.de

**Comment by acka47** [comment]
+1
