### ISSUE TITLE
Most facet counts only consider collections

### ISSUE THREAD

**Issue by fsteeg** [hbz/digitalisiertedrucke#42]
See http://beta.digitalisiertedrucke.de/

**Comment by acka47** [comment]
I am not sure whether the claim in issue title is actually correct or whether collections just have more information than titles. We will have to investigate this.

**Comment by fsteeg** [comment]
"Spache: Deutsch" shows 145 hits in http://digitalisiertedrucke.de/ but when we search its actually 83525 hits: http://digitalisiertedrucke.de/?size=20&q=*+AND+language:%22http://id.loc.gov/vocabulary/iso639-1/de%22

**Comment by acka47** [comment]
Closing
