### ISSUE TITLE
Restore old URLs

### ISSUE THREAD

**Issue by fsteeg** [hbz/digitalisiertedrucke#45]
Change routes to match the old URLs like `http://digitalisiertedrucke.de/record/46713`

Depends on #32

**Comment by fsteeg** [comment]
- [ ] When done, add beta & test URLs https://github.com/hbz/digitalisiertedrucke/wiki/Example-resources

**Comment by fsteeg** [comment]
We will keep the new pattern and IDs for collections, and restore the old ones for titles:

> Regarding the identifiers, we should keep using the literal ones for collections and look into using the /record/$ID pattern for single resources. Thus, we would regain old URLs for the biggest part of resources. -- @acka47 in https://github.com/hbz/digitalisiertedrucke/issues/32#issuecomment-256020938

**Comment by fsteeg** [comment]
For consistency with the `collections` URLs and the `D` and `P` IDs in digital and print titles, I've implemented this as a simple 301 moved permanently redirect, see URLs linked from 
https://github.com/hbz/digitalisiertedrucke/wiki/Example-resources:

http://test.digitalisiertedrucke.de/record/490805
http://test.digitalisiertedrucke.de/record/491265

**Comment by acka47** [comment]
http://www.digitalisiertedrucke.de/record/490805?ln=de currently doesn't redirect to http://digitalisiertedrucke.de/resources/490805. Shouldn't it already?

**Comment by fsteeg** [comment]
No, because the redirect functionality is not deployed to the production instance yet.

**Comment by acka47** [comment]
+1
