### ISSUE TITLE
Implement search UI

### ISSUE THREAD

**Issue by fsteeg** [hbz/digitalisiertedrucke#5]
Search box, result list, facets

**Comment by fsteeg** [comment]
Current internal staging deployment for testing and integration with #6: http://quaoar1.hbz-nrw.de:5001/

**Comment by fsteeg** [comment]
I've set up proxies with the current state at: http://dd.lobid.org and http://dd-test.lobid.org

This includes @SBRitter's work on #6.

I suggest we take this as a baseline, close #5 (this) and #6, and open detailed issues (I'll start with a few).

**Comment by acka47** [comment]
+1 Great starting point to improve on.
