### ISSUE TITLE
Display labels for field names and values

### ISSUE THREAD

**Issue by fsteeg** [hbz/digitalisiertedrucke#9]
- [x] Field values in search facets, see http://dd.lobid.org/?q=*
- [x] Field values in details pages, see http://dd.lobid.org/resources/P389288
- [x] Field names in search facets (facet headers), see http://dd.lobid.org/?q=*
- [x] Field names in details pages (left table column), see http://dd.lobid.org/resources/P389288

A single label mapping in applications.conf, used in both places, might make sense.

**Comment by acka47** [comment]
For DDC we might make use of https://github.com/hbz/lobid-rdf-to-json/blob/master/src/main/resources/labels.json

**Comment by acka47** [comment]
I suggest a separate file for properties. It's probably best when I edit this as soon as it is set up.

**Comment by acka47** [comment]
For DDC, see also https://github.com/hbz/etikett/blob/master/conf/ddc.turtle. It's only with German labels which suffices for our case.

**Comment by fsteeg** [comment]
Labels for facet values in search deployed to staging: http://dd-test.lobid.org/?q=*

DDC labels are indexed from the TTL file at:
https://raw.githubusercontent.com/hbz/etikett/master/conf/ddc.turtle

Type and medium labels are defined in the application.conf file:
https://github.com/hbz/digitalisiertedrucke/blob/9-labels/conf/application.conf#L29

Labels for the `isPartOf` facet are taken from the `title` field of the actual collection.

Based on this, we can use the labels in the details pages too (after #13, ping @SBRitter).

Updated title and original issue description to add labels for field names.

Adding @acka47 for review of the first item in https://github.com/hbz/digitalisiertedrucke/issues/9#issue-179168779.

**Comment by fsteeg** [comment]
Facet header labels deployed to staging: http://dd-test.lobid.org/?q=*

**Comment by SBRitter** [comment]
Labels for names and values deployed to staging: http://dd-test.lobid.org/resources/P389288 

However, still open: when label is empty (""), the table row gets rendered. This must be fixed.

**Comment by acka47** [comment]
+1 for the [example entry](http://test.digitalisiertedrucke.de/resources/P389288) and the facet labels.

There are at least two things missing: 

- Links to the collection description are missing
- In collection descriptions, labels for languages are missing, see e.g. http://beta.digitalisiertedrucke.de/collections/nordamericana.sub.goe.de

**Comment by fsteeg** [comment]
Deployed to staging:

Links to collections:
http://test.digitalisiertedrucke.de/resources/P389288
(note the second link does not work due to #26)

Language labels:
http://test.digitalisiertedrucke.de/collections/nordamericana.sub.goe.de

While working on the language labels, I've also set up a language facet:
http://test.digitalisiertedrucke.de/?q=*

**Comment by acka47** [comment]
+1

> While working on the language labels, I've also set up a language facet

Very nice.
